import {writeFile,mkdir,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {calibrationEngineHash} from './provenance.mjs';
import {nesChip,gbChip,mdChip,snesChip,c64Chip,instrumentsFor} from '../../packages/chipvoice/dist/index.js';
import {performanceInstrument} from '../../packages/chipvoice/dist/performance-palette.js';
import {calibrateMixInstrument,mixInstrumentSignature} from '../../packages/chipvoice/dist/mix-calibration.js';
const engineSha256=await calibrationEngineHash();
const out=`.artifacts/automatic-mixing/calibration/${engineSha256}`;await mkdir(out,{recursive:true});
const profiles=[];
for(const chip of [nesChip,gbChip,mdChip,snesChip,c64Chip]){
 const cases=new Map();
 const add=(voice,inst)=>{const key=voice+':'+mixInstrumentSignature(inst);cases.set(key,{voice,inst});};
 for(const role of ['lead','chord','bass'])for(let program=0;program<128;program+=8){
  const inst=performanceInstrument(chip.spec.id,role,program);
  const voice=chip.spec.id==='md'?'fm1':chip.spec.roles[role];
  if(chip.spec.id==='snes')for(const v of chip.spec.voices)add(v.id,inst);
  else add(chip.spec.id==='2a03'&&voice==='p2'?'p1':voice,inst);
 }
 const kit=instrumentsFor(chip.spec.id).perc;
 for(const drum of Object.values(kit))add(chip.spec.roles.perc,drum.instrument);
 // Source-native amplitude controls, independent of any song's identity.
 if(chip.spec.id==='2a03')for(const voice of ['p1','tri','noi'])for(const duty of voice==='p1'?[0,1,2,3]:[2])add(voice,{volume:[15],sustain:true,duty});
 for(const {voice,inst} of cases.values()){
  const key=createHash('sha256').update(JSON.stringify({chip:chip.spec.id,voice,signature:mixInstrumentSignature(inst),method:1})).digest('hex');
  let profile;
  try{profile=JSON.parse(await readFile(`${out}/${key}.json`));}catch(e){if(e.code!=='ENOENT')throw e;profile=calibrateMixInstrument(chip,voice,inst,{pitches:chip.spec.voices.find(v=>v.id===voice).notes==='period'?[0,3,7,11,15]:[36,48,60,72,84],durations:[.125,.5,1.5],controls:[0,1,3,7,11,15]});await writeFile(`${out}/${key}.json`,JSON.stringify(profile));}
  profiles.push(profile);console.log(chip.spec.id,voice,profiles.length,profile.rms.map(v=>v.toFixed(4)).join(','));
 }
}
await writeFile('packages/chipvoice/src/mix-profiles.ts',`// Generated by scores/mixing/calibrate.mjs; instrument probes, never song fits.\nimport type {MixProfile} from './mix-calibration.js';\nexport const MIX_FACTORY_PROFILES: readonly MixProfile[] = ${JSON.stringify(profiles)};\n`);
await writeFile(`${out}/manifest.json`,JSON.stringify({engineSha256,profiles:profiles.length,generatedAt:new Date().toISOString(),profileSha256:createHash('sha256').update(JSON.stringify(profiles)).digest('hex')},null,2));
await writeFile('scores/mixing/calibration-manifest.json',await readFile(`${out}/manifest.json`));
console.log('PASS factory calibration',profiles.length);
