import { build, context } from 'esbuild';
import fs from 'node:fs';

/**
 * The worklet, as a string.
 *
 * The driver hands the browser its processor as a blob URL, so the whole thing
 * has to be one self-contained script: a blob has no base URL for an import to
 * resolve against. This bundles `worklet.ts` and everything it reaches into
 * that script and writes it out as a TypeScript module exporting one string,
 * which the package imports like any other.
 *
 * Before this, the DSP was plain JavaScript with no imports so it could be
 * pasted into the worklet verbatim - and it was the one part of the package
 * the compiler never checked. Bundling makes "self-contained" a property of
 * the output rather than a rule the source has to keep.
 *
 *   node scripts/build-worklet.mjs           # once
 *   node scripts/build-worklet.mjs --watch   # on every change
 */
const ENTRY = 'src/chips/nes/worklet.ts';
const OUT = 'src/chips/nes/worklet-inline.ts';

const options = {
  entryPoints: [ENTRY],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2022',
  write: false,
  // Readable on purpose. The worklet shows up in devtools, and poking at the
  // chip from there is half of what the playground is for. It is 13 KB.
  minify: false,
  legalComments: 'none',
  logLevel: 'warning',
};

function emit(result) {
  const source = result.outputFiles[0].text;
  fs.writeFileSync(
    OUT,
    `// Generated by scripts/build-worklet.mjs from ${ENTRY}. Do not edit.\n` +
      `export const WORKLET_SOURCE = ${JSON.stringify(source)};\n`,
  );
  console.log(`${OUT}: ${source.length} bytes bundled from ${ENTRY}`);
}

if (process.argv.includes('--watch')) {
  const ctx = await context({
    ...options,
    plugins: [
      {
        name: 'emit',
        setup(b) {
          b.onEnd((result) => {
            if (result.errors.length === 0) emit(result);
          });
        },
      },
    ],
  });
  await ctx.watch();
  console.log(`watching ${ENTRY}`);
} else {
  emit(await build(options));
}
