import fs from 'node:fs';

/**
 * One DSP source, two shapes.
 *
 * `src/chips/nes/dsp.js` is the chip and nothing else: no imports, no host
 * globals, so it can be read by both worlds that need it. Neither can read it
 * directly, though - a worklet has no `import`, and the package is ESM so a
 * bare `.js` file cannot use `module.exports`. So this generates both:
 *
 *   dsp.generated.ts   the same code with an ESM export, for Node and bundlers
 *   worklet-inline.ts  the same code plus the worklet shell, as a string
 *
 * Generated files are git-ignored. The source of truth is the one file a human
 * edits, which is the whole point of doing it this way rather than keeping two
 * copies in step by hand.
 */
const DIR = 'src/chips/nes';
const dsp = fs.readFileSync(`${DIR}/dsp.js`, 'utf8');
const shell = fs.readFileSync(`${DIR}/worklet-shell.js`, 'utf8');

const banner = (source) =>
  `// Generated by scripts/build-dsp.mjs. Do not edit.\n// Source of truth: ${source}\n`;

// ---- the module form
fs.writeFileSync(
  `${DIR}/dsp.generated.ts`,
  banner(`${DIR}/dsp.js`) +
    '// @ts-nocheck - this is hand-written DSP JavaScript, typed at its boundary\n' +
    '// by chip.ts rather than inside the hot loop, where annotations would be\n' +
    '// noise and every value is a number anyway.\n' +
    dsp +
    '\nexport { NesApuCore, CPU_HZ };\n',
);

// ---- the worklet form
//
// JSON.stringify rather than a template literal. An earlier version pasted the
// source between backticks and refused to build if it found one - which meant
// no JSDoc in the DSP could quote a symbol, and the first comment written after
// that broke the build for a reason that had nothing to do with the code.
// Escaping is the fix; forbidding was the bug.
const worklet = dsp + shell;
fs.writeFileSync(
  `${DIR}/worklet-inline.ts`,
  banner(`${DIR}/dsp.js` + ' + worklet-shell.js') +
    `export const WORKLET_SOURCE = ${JSON.stringify(worklet)};\n`,
);

console.log(`dsp.generated.ts and worklet-inline.ts built from ${dsp.length} bytes of DSP`);
