'use client';
import {useT} from '@/i18n/react';
import Link from '@/i18n/react';
import {SiteHeader, SiteFooter} from '@/ui/components';

export default function About() {
 const t = useT();
  return <><SiteHeader active="about"/><main className="demo-main about-main">
    <span className="micro">{t("BEHIND THE SOUND")}</span>
    <h1>{t("A tiny orchestra.")}<br/>{t("Made of code.")}</h1>
    <p>{t("chipvoice is an open-source JavaScript library that recreates classic console sound chips. This site is an instrument you can play to hear what the library does.")}</p>
    <section><h2>{t("From score to sound.")}</h2><p>{t("A score becomes notes, notes become chip instructions, and the emulated chip generates the audio. Change the console and the same music takes on a different voice. The complete-arrangement player starts with lossless recordings rendered by these engines. Tempo, pitch and part edits, and your own MIDI files, render locally in a worker while the current music keeps playing.")}</p><p>{t("Pulse waves and noise on Famicom. Wavetables on Game Boy. FM synthesis on Mega Drive. Sample playback, envelopes and echo on Super Famicom. Each engine follows its own hardware rules; Super Famicom uses a small sample bank, just as its sound chip did.")}</p><p>{t("The engines are written in TypeScript and run as JavaScript. Open Make a loop for live synthesis in an AudioWorklet: play notes, trigger effects, record and edit your own score. The same library powers these live instruments and the full-arrangement renders.")}</p></section>
    <section><h2>{t("The limits are part of the music.")}</h2><p>{t("Those consoles had only a handful of voices. A jump or a coin sound could borrow a channel from the music. Try the effect pads in Make a loop and watch it happen. The goal is a small, reusable audio engine for games, instruments and playful websites, with those constraints built in.")}</p><p>{t("Choose a melody or console to start the playground. Your browser needs that first interaction to enable sound. Once playing, console and tempo changes flow into the next sound. Press Pause in the arrangement player to hold your position until you play again.")}</p></section>
    <section><h2>{t("Familiar notes. Honest comparisons.")}</h2><p>{t("Mario, Zelda and Sonic open on their original console with the game’s chip commands and an independent reference to compare. NES commands are verified in CPU cycles; Mega Drive commands follow the original VGM capture. Other consoles and musical edits use adaptations extracted from those commands. No accompaniment is invented.")}</p><p>{t("The ")}<Link href="/lab">{t("listening lab")}</Link>{t(" uses versioned lossless recordings for repeatable, level-matched comparisons. It starts only when you press Play. Source checks compare pitches, rhythms and rests; engine checks compare register replay and, for Super Famicom, a native DSP reference. The lab publishes the evidence beside the audio.")}</p><p>{t("The public selector currently features four Japanese consoles. C64 support remains in the library and existing saved scores.")}</p></section>
    <section><h2>{t("Take it into your own project.")}</h2><pre><code>npm install chipvoice</code></pre><p>{t("Make a tune in the playground, open “View code”, and use the score in your own project. The library, examples, fidelity methodology and backlog are all on ")}<a href="https://github.com/gwendall/chipvoice#readme">{t("GitHub")}</a>.</p><Link href="/" className="small-button">{t("Play with the sound →")}</Link></section>
    <section id="credits"><h2>{t("Credits & sources.")}</h2><p>{t("Music by Koji Kondo (Mario and Zelda) and Masato Nakamura (Sonic). Each arrangement’s source, transcription or native reference and exact coverage appear under the console. See the ")}<a href="https://github.com/gwendall/chipvoice/tree/main/scores">{t("score methodology and reference ledgers")}</a>.</p><p>{t("Console marks are bundled locally from Wikimedia Commons, preserving their source colours: ")}<a href="https://commons.wikimedia.org/wiki/File:Family_Computer_logo.svg">{t("Famicom")}</a>, <a href="https://commons.wikimedia.org/wiki/File:Gameboy_logo.svg">{t("Game Boy")}</a>, <a href="https://commons.wikimedia.org/wiki/File:MegaDriveJPLogo.svg">{t("Mega Drive (Japan)")}</a>{t(" and ")}<a href="https://commons.wikimedia.org/wiki/File:Super_Famicom_logo.svg">{t("Super Famicom")}</a>{t(". The Game Boy wordmark is monochrome in its source.")}</p><p>{t("Marks identify the emulated consoles. Nintendo and Sega retain their respective trademarks; this independent project is not affiliated with them. Archived marks from ")}<a href="https://github.com/HVR88/Monochrome-Gaming-Logos">{t("HVR88’s Monochrome Gaming Logos")}</a>{t(" remain credited in the ")}<a href="https://github.com/gwendall/chipvoice/blob/main/apps/web/public/machines/README.md">{t("asset manifest")}</a>.</p></section>
  </main><SiteFooter/></>;
}
