import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '../..');

const ENGINE_LABEL = { chromium: 'Chromium', firefox: 'Firefox', webkit: 'WebKit (Playwright\'s stand-in for Safari, not Safari itself)' };
const ENGINE_LABEL_JA = { chromium: 'Chromium', firefox: 'Firefox', webkit: 'WebKit（PlaywrightのSafari代替、Safari本体ではない）' };

function engineRow(name, result, label) {
  if (!result) return `| ${label} | - | not run |`;
  if (!result.installed) return `| ${label} | - | ${result.reason ?? 'not installed locally'} |`;
  const mismatches = result.rows.filter(r => !r.match).length;
  return `| ${label} | ${result.version} | ${mismatches === 0 ? `all ${result.rows.length} match` : `${mismatches}/${result.rows.length} mismatch`} |`;
}

function inputsTable(report, engineNames, labels) {
  const header = `| Input | Kind | Chip | Seconds | Node SHA-256 | ${engineNames.map(n => labels[n].split(' ')[0]).join(' | ')} |`;
  const sep = `| --- | --- | --- | --- | --- | ${engineNames.map(() => '---').join(' | ')} |`;
  const rows = report.node.map(row => {
    const cells = engineNames.map(name => {
      const engine = report.engines[name];
      if (!engine || !engine.installed) return '-';
      const r = engine.rows.find(x => x.id === row.id);
      return r?.match ? 'match' : 'MISMATCH';
    });
    return `| ${row.id} | ${row.kind} | ${row.chip} | ${row.seconds.toFixed(1)} | \`${row.sha256.slice(0, 16)}…\` | ${cells.join(' | ')} |`;
  });
  return [header, sep, ...rows].join('\n');
}

function inputsTableJa(report, engineNames) {
  const header = `| 入力 | 種類 | チップ | 秒数 | Node SHA-256 | ${engineNames.map(n => ENGINE_LABEL[n].split(' ')[0]).join(' | ')} |`;
  const sep = `| --- | --- | --- | --- | --- | ${engineNames.map(() => '---').join(' | ')} |`;
  const rows = report.node.map(row => {
    const cells = engineNames.map(name => {
      const engine = report.engines[name];
      if (!engine || !engine.installed) return '-';
      const r = engine.rows.find(x => x.id === row.id);
      return r?.match ? '一致' : '不一致';
    });
    return `| ${row.id} | ${row.kind} | ${row.chip} | ${row.seconds.toFixed(1)} | \`${row.sha256.slice(0, 16)}…\` | ${cells.join(' | ')} |`;
  });
  return [header, sep, ...rows].join('\n');
}

function diagnosisSection(report, engineNames) {
  const lines = [];
  for (const name of engineNames) {
    const engine = report.engines[name];
    if (!engine?.installed) continue;
    for (const row of engine.rows) {
      if (!row.match && row.diagnosis) lines.push(`- ${ENGINE_LABEL[name]}, \`${row.id}\`: first differing sample ${row.diagnosis.firstSample}, max absolute difference ${row.diagnosis.maxDelta}, RMS error ${row.diagnosis.rmsError}.`);
    }
  }
  return lines;
}
function diagnosisSectionJa(report, engineNames) {
  const lines = [];
  for (const name of engineNames) {
    const engine = report.engines[name];
    if (!engine?.installed) continue;
    for (const row of engine.rows) {
      if (!row.match && row.diagnosis) lines.push(`- ${ENGINE_LABEL_JA[name]}、\`${row.id}\`: 最初に異なったサンプル ${row.diagnosis.firstSample}、絶対差の最大値 ${row.diagnosis.maxDelta}、RMS誤差 ${row.diagnosis.rmsError}。`);
    }
  }
  return lines;
}

/** Writes `docs/RENDER-PARITY.md` and its Japanese mirror from a `compareEngines` report. */
export async function writeRenderParityDocs(report, { revision, createdAt, webUrl }) {
  const engineNames = ['chromium', 'firefox', 'webkit'];
  const totalMismatches = engineNames.reduce((sum, name) => { const e = report.engines[name]; return sum + (e?.installed ? e.rows.filter(r => !r.match).length : 0); }, 0);
  const diagnosis = diagnosisSection(report, engineNames);
  const diagnosisJa = diagnosisSectionJa(report, engineNames);

  const en = `# Render parity

<p align="center">
  <a href="RENDER-PARITY.md">English</a> &bull;
  <a href="RENDER-PARITY_ja.md">日本語</a>
</p>

MIX-14: does the same fixed set of inputs render to the same PCM in Node and in every browser engine this project can automate. Generated by \`pnpm render-parity:sheet\`; do not hand-edit the tables.

<a id="what-this-measures"></a>

## What this measures

A fixed, small set of ${report.node.length} inputs (a short excerpt of each published arrangement on every chip it plays on, plus a couple of instrument-catalogue presets per chip so the C64 - which no published arrangement reaches - is covered too). Every input is a \`PerformancePlan\`, rendered through \`renderPerformance\` from \`packages/chipvoice/dist\` - the exact function Node's own offline render and, by construction (the same \`ChipCore\` class the AudioWorkletProcessor instantiates), the site's real-time playback path both build on. The comparison hashes the raw float32 PCM bytes (SHA-256), never the 16-bit \`toWav\` output, so a difference far smaller than a WAV file could show still moves the hash.

<a id="last-run"></a>

## Last run

- Date: ${createdAt}
- Revision: \`${revision}\`
- Node: ${report.nodeVersion}

| Engine | Version | Result |
| --- | --- | --- |
${engineNames.map(name => engineRow(name, report.engines[name], ENGINE_LABEL[name])).join('\n')}

<a id="results"></a>

## Results

${inputsTable(report, engineNames, ENGINE_LABEL)}

${totalMismatches === 0 ? 'Every environment above produced byte-identical PCM for every input.' : `${totalMismatches} mismatch(es) found. Diagnosis:\n\n${diagnosis.join('\n')}`}

<a id="what-still-needs-a-person"></a>

## What still needs a person

Playwright's WebKit is the closest automatable stand-in for Safari available in CI or on a workstation, but it is not Safari itself, and none of the engines above are a physical phone. Two things stay manual:

- **Real Safari** (macOS or iOS), which Playwright cannot launch.
- **Physical phones**, whose audio path (a real DAC, a real browser build tied to that OS version) nothing in this repository can stand in for.

Open **${webUrl}** on the device to check. It fetches the same fixed inputs this sheet uses (a shorter excerpt of each, so the page stays light), renders them in that browser with the same \`renderPerformance\` call, and shows each input's hash next to the Node reference used to build the page - a match or a mismatch per input, no setup beyond opening the page. It takes about a minute: open the link, wait for every row to finish, and note whether every row matches. A mismatch is worth reporting with the device, OS and browser version shown on the page.

<a id="what-runs-in-ci"></a>

## What runs in CI

\`pnpm render-parity:check\` (Node against Chromium only) runs on every push and pull request. Firefox and WebKit need binaries CI does not install, so the full matrix above is \`pnpm render-parity:sheet\`, run locally and committed here.
`;

  const ja = `# レンダーの一致性

<a id="render-parity"></a>
<p align="center">
  <a href="RENDER-PARITY.md">English</a> &bull;
  <a href="RENDER-PARITY_ja.md">日本語</a>
</p>

MIX-14: 固定した入力セットがNodeと、自動化できるすべてのブラウザエンジンで同じPCMにレンダーされるかを確認します。\`pnpm render-parity:sheet\`で生成され、表を手で編集しないでください。

<a id="what-this-measures"></a>

## この測定が示すもの

固定された${report.node.length}件の小さな入力セット（公開済みの各アレンジメントを、それが再生できる各チップで短く切り出したもの、加えて、公開アレンジメントが到達しないC64をカバーするため各チップにつき数個の音色カタログのプリセット）。すべての入力は\`PerformancePlan\`であり、\`packages/chipvoice/dist\`の\`renderPerformance\`でレンダーされます。これはNode自身のオフラインレンダーと、（AudioWorkletProcessorがインスタンス化するのと同じ\`ChipCore\`クラスであることにより）サイトのリアルタイム再生パスの両方が使う関数そのものです。比較は生のfloat32 PCMバイトのSHA-256ハッシュを取り、16ビットの\`toWav\`出力は使いません。WAVファイルでは示せないほど小さな差でもハッシュが変わります。

<a id="last-run"></a>

## 直近の実行

- 日付: ${createdAt}
- リビジョン: \`${revision}\`
- Node: ${report.nodeVersion}

| エンジン | バージョン | 結果 |
| --- | --- | --- |
${engineNames.map(name => engineRow(name, report.engines[name], ENGINE_LABEL_JA[name])).join('\n')}

<a id="results"></a>

## 結果

${inputsTableJa(report, engineNames)}

${totalMismatches === 0 ? '上記のすべての環境が、すべての入力についてバイト単位で同一のPCMを生成しました。' : `${totalMismatches} 件の不一致が見つかりました。診断:\n\n${diagnosisJa.join('\n')}`}

<a id="what-still-needs-a-person"></a>

## 人手がまだ必要な部分

PlaywrightのWebKitはCIやワークステーションで自動化できる中で最もSafariに近い代替ですが、Safari本体ではなく、上記のどのエンジンも実機のスマートフォンではありません。次の2つは手動のままです。

- **実際のSafari**（macOSまたはiOS）。Playwrightでは起動できません。
- **実機のスマートフォン**。その音声経路（実際のDAC、そのOSバージョンに紐づく実際のブラウザビルド）はこのリポジトリの何によっても代替できません。

確認するには、その端末で **${webUrl}** を開いてください。このシートと同じ固定入力セット（ページを軽く保つため、それぞれ短く切り出したもの）を取得し、同じブラウザで同じ\`renderPerformance\`呼び出しを使ってレンダーし、ページを構築したNodeの参照値の横に各入力のハッシュを表示します。入力ごとに一致・不一致が分かり、ページを開く以外の準備は不要です。所要時間は約1分です。リンクを開き、すべての行が終わるのを待ち、すべての行が一致するか確認してください。不一致があれば、ページに表示される端末・OS・ブラウザのバージョンとともに報告する価値があります。

<a id="what-runs-in-ci"></a>

## CIで実行される内容

\`pnpm render-parity:check\`（NodeとChromiumのみ）はすべてのpushとpull requestで実行されます。FirefoxとWebKitはCIがインストールしないバイナリを必要とするため、上記の完全なマトリクスは\`pnpm render-parity:sheet\`としてローカルで実行し、ここにコミットします。
`;

  await writeFile(resolve(root, 'docs/RENDER-PARITY.md'), en);
  await writeFile(resolve(root, 'docs/RENDER-PARITY_ja.md'), ja);
}
