import type {Metadata} from 'next';
import Link from 'next/link';
import {SiteHeader, SiteFooter} from '../../ui/components';

export const metadata: Metadata = {
  title: 'About chipvoice · Sound chips, rebuilt in JavaScript',
  description: 'How chipvoice turns text scores into console sound, why hardware constraints matter, and how we check the music.',
};

export default function About() {
  return <><SiteHeader active="about"/><main className="demo-main about-main">
    <span className="micro">BEHIND THE SOUND</span>
    <h1>A tiny orchestra.<br/>Made of code.</h1>
    <p>chipvoice is an open-source JavaScript library that recreates classic console sound chips. This site is an instrument you can play to hear what the library does.</p>
    <section><h2>The browser makes the sound.</h2><p>In the playground, a text score becomes notes, notes become chip instructions, and the emulated chip generates the audio. Change the console and the same melody takes on a different voice. Change the tempo or play a note and hear it happen live.</p><p>Pulse waves and noise on Famicom. Wavetables on Game Boy. FM synthesis on Mega Drive. Sample playback, envelopes and echo on Super Famicom. Each engine follows its own hardware rules; Super Famicom uses a small sample bank, just as its sound chip did.</p><p>The engines are written in TypeScript and run as JavaScript in an AudioWorklet. The playground synthesizes the music locally instead of streaming a finished soundtrack.</p></section>
    <section><h2>The limits are part of the music.</h2><p>Those consoles had only a handful of voices. A jump or a coin sound could borrow a channel from the music. Try the effect pads and watch it happen. The goal is a small, reusable audio engine for games, instruments and playful websites, with those constraints built in.</p><p>Choose a melody or console to start the playground. Your browser needs that first interaction to enable sound. Once playing, console and tempo changes flow into the next sound. Press Stop and the music stays stopped until you play again.</p></section>
    <section><h2>Familiar notes. Honest comparisons.</h2><p>Mario, Zelda and Sonic make it easier to recognise what changes. These are melody arrangements checked against reference transcriptions, with no invented bass or drum parts. They demonstrate our instrument palette; they do not reproduce each game’s complete soundtrack or original instruments.</p><p>The <Link href="/lab">listening lab</Link> uses versioned lossless recordings for repeatable, level-matched comparisons. It starts only when you press Play. Source checks compare pitches, rhythms and rests; engine checks compare register replay and, for Super Famicom, a native DSP reference. The lab publishes the evidence beside the audio.</p><p>The public selector currently features four Japanese consoles. C64 support remains in the library and existing saved scores.</p></section>
    <section><h2>Take it into your own project.</h2><pre><code>npm install chipvoice</code></pre><p>Make a tune in the playground, open “View code”, and use the score in your own project. The library, examples, fidelity methodology and backlog are all on <a href="https://github.com/gwendall/chipvoice#readme">GitHub</a>.</p><Link href="/" className="small-button">Play with the sound →</Link></section>
    <section id="credits"><h2>Credits & sources.</h2><p>Music by Koji Kondo (Mario and Zelda) and Masato Nakamura (Sonic). Each melody’s source, transcriber and exact coverage appear under the console. See the <a href="https://github.com/gwendall/chipvoice/tree/main/scores">score methodology and reference ledgers</a>.</p><p>Console marks are bundled locally from Wikimedia Commons, preserving their source colours: <a href="https://commons.wikimedia.org/wiki/File:Family_Computer_logo.svg">Famicom</a>, <a href="https://commons.wikimedia.org/wiki/File:Gameboy_logo.svg">Game Boy</a>, <a href="https://commons.wikimedia.org/wiki/File:MegaDriveJPLogo.svg">Mega Drive (Japan)</a> and <a href="https://commons.wikimedia.org/wiki/File:Super_Famicom_logo.svg">Super Famicom</a>. The Game Boy wordmark is monochrome in its source.</p><p>Marks identify the emulated consoles. Nintendo and Sega retain their respective trademarks; this independent project is not affiliated with them. Archived marks from <a href="https://github.com/HVR88/Monochrome-Gaming-Logos">HVR88’s Monochrome Gaming Logos</a> remain credited in the <a href="https://github.com/gwendall/chipvoice/blob/main/apps/web/public/machines/README.md">asset manifest</a>.</p></section>
  </main><SiteFooter/></>;
}
