import assert from 'node:assert/strict';
import {measureAudio, comparePcm, spectrum} from './metrics.mjs';
import {listeningLevels} from './levels.mjs';
const sampleRate = 44100;
const sine = (hz, amplitude = .5) => Float32Array.from({length:sampleRate}, (_, i) => amplitude * Math.sin(2 * Math.PI * hz * i / sampleRate));
const pcm = left => ({left, sampleRate});
const tone = pcm(sine(440)), silent = pcm(new Float32Array(sampleRate));
const metrics = measureAudio(tone);
assert.ok(Math.abs(metrics.rmsDbFS - (-9.0309)) < .001);
assert.ok(Math.abs(metrics.samplePeakDbFS - (-6.0206)) < .001);
assert.ok(Math.abs(metrics.dc) < 1e-8);
assert.equal(metrics.clippedSamples, 0);
assert.equal(measureAudio(silent).rmsDbFS, null);
assert.equal(spectrum(silent).centroidHz, null);
assert.ok(Math.abs(spectrum(tone).centroidHz - 440) < 2);
const opposite = { ...tone, right: Float32Array.from(tone.left, value => -value) };
assert.ok(Math.abs(measureAudio(opposite).stereoCosine + 1) < 1e-10);
assert.ok(Math.abs(spectrum(opposite).centroidHz - 440) < 2);
// Mutation controls: silence, altered pitch, gain, a single corrupt sample.
assert.equal(comparePcm(tone, silent).ok, false);
assert.equal(comparePcm(tone, pcm(sine(450))).ok, false);
assert.equal(comparePcm(tone, pcm(sine(440,.49))).ok, false);
const altered = pcm(tone.left.slice()); altered.left[123] = NaN;
assert.equal(measureAudio(altered).invalidSamples, 1);
assert.equal(comparePcm(tone, altered).ok, false);
assert.ok(measureAudio(pcm(sine(440,1.1))).clippedSamples > 0);
assert.equal(comparePcm(tone, pcm(tone.left.slice())).ok, true);
const stereo = { ...tone, right: tone.left }, changed = { ...pcm(tone.left.slice()), right: tone.left.slice() };
changed.left[50] += .1; changed.right[20] += .1;
assert.equal(comparePcm(stereo,changed).firstSample,20);
const entry = (lufs,rms) => ({loudness:{integratedLUFS:lufs},metrics:{rmsDbFS:rms}});
const matched = listeningLevels([entry(-12,-15),entry(-18,-21)]);
assert.equal(matched.method,'LUFS');
assert.ok(Math.abs(20*Math.log10(matched.gains[0]) - 20*Math.log10(matched.gains[1]) + 6) < 1e-10);
assert.ok(matched.gains.every(gain => gain <= 1));
const fallback = listeningLevels([entry(-12,-15),entry(null,-21)]);
assert.match(fallback.method,/RMS/);
assert.ok(Math.abs(20*Math.log10(fallback.gains[0]) - 20*Math.log10(fallback.gains[1]) + 6) < 1e-10);
assert.deepEqual(listeningLevels([entry(null,null)]).gains,[0]);
console.log('PASS listening metrics detect silence, pitch/gain changes, invalid/clipped PCM and stereo cancellation; level matching uses a common scale');
